image: python:3.7

stages:
   - deploy

before_script:
   - git remote show
   - git remote show origin
   - pip install -r requirements.txt


dpl_ghpages:
   stage: deploy
   only:
      - master
   tags:
      - evo
   script:
      - rm -rf output
      - git clone --depth 1 --single-branch --branch gh-pages https://Shogoki:$GITHUB_ACCESS_TOKEN@github.com/Shogoki/drbucur.com.git gh-pages
      -  make publish
      - cp -Rpf output/* gh-pages/
      - cd gh-pages
      - git add -A
      - git config --global user.email "shogoki@gamersvillage.de"
      - git config --global user.name "Gitlab Runner"
      - git commit -m "Build from $CI_SERVER_NAME $CI_PIPELINE_ID"
      - git push 

