#image: python:3.7

stages:
   - deploy

before_script:
   - git remote show
   - git remote show origin
   - pip install -r requirements.txt


dpl_ghpages:
   stage: deploy
   only:
      - master
   tags:
      - evo
      - shell
   script:
      - make github

