name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      name: "Checkoput Repo"
    - name: Pelican for GitHub Pages
      uses: nelsonjchen/gh-pages-pelican-action@0.1.4
